# render.yaml - Render Infrastructure as Code
services:
  # PostgreSQL Database
  - type: pserv
    name: personal-expense-tracker-db
    env: postgresql
    plan: free
    databaseName: personal_expense_tracker
    user: expense_user

  # Backend Web Service
  - type: web
    name: personal-expense-tracker-backend
    env: java
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: chmod +x render-start.sh && ./render-start.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        fromDatabase:
          name: personal-expense-tracker-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"

  # Frontend Static Site
  - type: web
    name: personal-expense-tracker-frontend
    env: static
    plan: free
    buildCommand: echo "Static files ready"
    staticPublishPath: ./src/main/resources/static
    envVars:
      - key: API_URL
        fromService:
          name: personal-expense-tracker-backend
          type: web
          property: host